### ISSUE TITLE
Can't seem to get it working

### ISSUE THREAD

**Issue by AlessandroEmm** [Download/undertow-cors-filter#1]
Hey there

I tried getting your filter to run but I cannot seem to get it to append any headers what so ever.

My current config is:

```
<filters>
  <filter name="undertow-cors-filter" class-name="com.stijndewitt.undertow.cors.Filter" module="com.stijndewitt.undertow.cors">
  <param name="urlPattern" value="^/auth/.*" />
   <param name="policyClass" value="com.stijndewitt.undertow.cors.AllowAll" />
</filter>
```

To make things simpler i removed the param with the urlPattern but that resulted in a lot of nullpointer exception so it seems to be necessary in the current version. This also sort of tought me that the installation of the module/filter itself must be correct.

But even with the urlPattern I haven't seen any CORS headers appended in my requests - what could be wrong? I took the latest state from master.

Thanks a lot for your help
Alessandro

**Comment by Download** [comment]
Hi Alessandro,

Sorry for the late response. Did you get this to work?
My work on this project got interrupted so it's not quite ready for prime time but it should work if configured correctly.

I would be interested in the NullPointerExceptions you saw. If you can create an issue for it and attach the stack trace I will try to fix it.

If you have any other questions/problems, please respond here and I will keep an eye out for this thread in the coming days to help you if I can.

**Comment by Download** [comment]
@AlessandroEmm 
Will try to get this published to Maven Central and make sure the [example is more clear](https://github.com/Download/undertow-cors-filter/pull/2).

**Comment by Download** [comment]
@AlessandroEmm 
Please try the current release (0.4.0). Also have a look at the README, I updated it to make it more clear. Also the docs about urlPattern were wrong which is probably why you could not get it to work.

Sorry for the bumpy ride but I'm still working towards 1.0. The current release could be promoted to 1.0.0 as-is if I don't find any issues. I'd be very interested in feedback from your end.

**Comment by Download** [comment]
Feel free to re-open if you have any questions.

**Comment by bekihm** [comment]
I have the also the problem with the NullPointerException. The following stacktrace is shown in keycloak log:
`14:07:20,761 ERROR [io.undertow.request] (default task-1) UT005071: Undertow request failed HttpServerExchange{ OPTIONS /auth/realms/apiman/protocol/openid-connect/auth request {Accept=[*/*], Accept-Language=[de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7], Access-Control-Request-Method=[GET], Accept-Encoding=[gzip, deflate, br], Origin=[http://localhost:8181], User-Agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36], Access-Control-Request-Headers=[x-requested-with], Connection=[keep-alive], Host=[localhost:8383]} response {}}: java.lang.NullPointerException
        at java.util.regex.Pattern.<init>(Pattern.java:1350)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at com.stijndewitt.undertow.cors.Filter.handleRequest(Filter.java:665)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.lang.Thread.run(Thread.java:748)`

My configuration in the standalone.xml is the following:
`        <subsystem xmlns="urn:jboss:domain:undertow:6.0" default-server="default-server" default-virtual-host="default-host" default-servlet-container="default" default-security-domain="other">
            <buffer-cache name="default"/>
            <server name="default-server">
                <http-listener name="default" socket-binding="http" redirect-socket="https" enable-http2="true"/>
                <https-listener name="https" socket-binding="https" security-realm="ApplicationRealm" enable-http2="true"/>
                <host name="default-host" alias="localhost">
                    <location name="/" handler="welcome-content"/>
                    <http-invoker security-realm="ApplicationRealm"/>
                    <filter-ref name="undertow-cors-filter" />
                </host>
            </server>
            <servlet-container name="default">
                <jsp-config/>
                <websockets/>
            </servlet-container>
            <handlers>
                <file name="welcome-content" path="${jboss.home.dir}/welcome-content"/>
            </handlers>
            <filters>
                <filter name="undertow-cors-filter" class-name="com.stijndewitt.undertow.cors.Filter" module="com.stijndewitt.undertow.cors">
                </filter>
            </filters>
        </subsystem>`

Update: Sorry for the poor formatting

**Comment by bekihm** [comment]
The build of the master works. The issue was the wrong location of the module. 
Wrong:
\modules\com\stijndewitt\undertow\cors\main
Right:
\modules\system\layers\base\com\stijndewitt\undertow\cors\main

**Comment by Download** [comment]
Sorry for my lack of response earlier. This is a hobby project so it does not always get enough attention. Great to hear you resolved your issue.

If you have any feedback for me on how to improve the docs or anything I'd be interested to know. Also if you would be willing to share what you are working on that would be cool. I would love to have a section here somewhere saying this software is being used by companies X, Y and Z  :)

**Comment by viggis75** [comment]
@bekihm can you explain exactly what you did to make it work? I struggle with the same, but I didn't understand the thing you wrote about
\modules\com...
vs 
\modules\system


is it the 0.4.0 of the jar which is wrong, or is it the configuration in standalone.xml?

(cc @Download )

**Comment by bekihm** [comment]
The files in the "undertow-cors-filter-0.4.0-bin.zip" have the wrong folder structure. If you follow the current documentation you copy the files on the wrong place:
"To use this filter, install it as a module in WildFly / EAP. Grab the module zip file from Maven Central and unzip it in the root of your JBoss installation folder." (The module is then placed under "\modules\com\stijndewitt\undertow\cors\main" which is wrong).

The right place for the module is "\modules\system\layers\base\com\stijndewitt\undertow\cors\main". So you have to copy the content of the module directory of the "undertow-cors-filter-0.4.0-bin.zip" under the path "\modules\system\layers\base\" in your WildFly / EAP installation folder.
If you now check the path it should be "\modules\system\layers\base\com\stijndewitt\undertow\cors\main" where the"module.xml" and "undertow-cors-filter-0.4.0.jar" is placed.

I hope this helps you @viggis75 .

@Download : I think the documentation has to be changed (or the structure in the undertow-cors-filter-0.4.0-bin.zip).

**Comment by Download** [comment]
@viggis75 @bekihm 
Thanks guys for looking into this. As you may guess from the version number, `undertow-cors-filter` is not completely mature yet, hence the growing pains. 

Basically I wrote this project because I needed CORS headers working correctly on my server and this filter was the only way I could get that done. I did some work to make the filter generic and configurable and to document how to use and extend it and that's where it's at now. So when you decide to use this filter, know that it is Open Source in the trueest sense of the word; I am just me. There is no company backing me in any way. All time I invest(ed) in this came out of my own free time. There is no warranty whatsoever, of any kind. I might die tomorrow and you will be on your own. :)

Having said that I am really glad that you guys are actively using it or at least trying to do so and I hope it works for you. If so I would really appreciate an issue/comment about it. If possible, send me a link to your website. It's awesome to know people are using your code. And I would like to challenge you guys to pick up the ball. As you have noticed this project is not finished yet. There are docs to fix, or the JAR on Maven Central should get a different shape. And probably we will find more issues when we use it more. So if you have solved an issue and you know about it and what should change in this project, I beg you, please create a Pull Request:

1. Fork this project
2. Clone from your fork to your local machine
3. Create a new Branch. Call it 'docs-update' or 'change-zip-folder-structure' or something
4. Implement your changes in this new branch
5. Commit your changes to your fork
6. In your Github fork, there will be a button 'Create Pull Request'.... Press it!!
7. I **will** review your code and merge it
8. I will make you a collaborator on this repo 👍 

I can do the version updating and publishing to Maven Central etc. for now (as it is a somewhat involved process) but I need other people to step up and invest time in this as well or otherwise I cannot afford to spend time on this at the moment.

EDIT:
If the above steps seem daunting to you; I am absolutely willing to invest time in helping you get set up with developing on this filter. And from a learning standpoint I think you will find that if you do, you will get a complete understanding of how this filter works and find that it's not all that complicated. You will have 'mastered' it. :)

Share the love!

-Stijn
