### ISSUE TITLE
Duplicate CORS-headers

### ISSUE THREAD

**Issue by viggis75** [Download/undertow-cors-filter#4]
It seems that when adding the undertow-cors-filter, it adds headers even though they already exist. I tweaked the logging, and *at the time of checking if the header already exists, it doesn't*. It means that the CORS headers are added later in the filter chain by undertow.

Before adding the undertow-cors-filter, it seems Undertow adds the CORS headers for the OPTIONS (preflight) call, but not for the GET call. After adding the undertow-cors-filter, it duplicates the headers on the OPTIONS call.

**Comment by Download** [comment]
Hi @viggis75 , can you tell a bit more about your setup? What is your filter configuration? Can you post it? Also, what do you mean when you say 'Undertow adds the CORS headers'? Are you saying that even without the undertow-cors-filter installed, Undertow is already adding CORS headers to some requests? If so that would surprise me because AFAIK, Undertow does not add such headers by itself unless there is some other filter/servlet/jax-rs component etc doing that.

**Comment by viggis75** [comment]
Here is my filter configuration:
```
<filter name="undertow-cors-filter" class-name="com.stijndewitt.undertow.cors.Filter" module="com.stijndewitt.undertow.cors">
                        <!-- which requests should be filtered? defaults to "^.*$", matching all requests -->
                        <param name="urlPattern" value="^.*$" />

                        <!-- which policy should be used? defaults to AllowAll -->
                        <param name="policyClass"       value="com.stijndewitt.undertow.cors.AllowAll" />
                        <!-- alternative policy: AllowMatching -->
                        <!-- param name="policyClass"      value="com.stijndewitt.undertow.cors.AllowMatching" /-->
                        <!-- param name="policyParam"      value="^http(s)?://(www\.)?example\.(com|org)$" /-->
                        <!-- alternative policy: Whitelist -->
                        <!-- param name="policyClass"      value="com.stijndewitt.undertow.cors.Whitelist" /-->
                        <!-- param name="policyParam"      value="${jboss.server.data.dir}/whitelist.txt" /-->

                        <!-- which CORS headers should be set? values listed are the defaults -->
                        <!-- param name="exposeHeaders"    value="Accept-Ranges,Content-Length,Content-Range,ETag,Link,Server,X-Total-Count" /-->
                        <!-- param name="maxAge"           value="864000" /-->
                        <!-- param name="allowCredentials" value="true" /-->
                        <param name="allowMethods"     value="GET,POST" />
                        <param name="allowHeaders"     value="Authorization,Content-Type,Link,X-Total-Count,Range" />
                </filter>
```


I have tried my setup (Frontend, Keycloak server, microservice) with and without Docker, and it seems to work (Cors headers being sent correctly without Docker), but when my microservice is run within a Docker container, only the OPTIONS response has the Cors headers, the following Get does not. 

I have made a google document I can share with you where I've put some screenshots from the network tab showing the request+responses @Download

**Comment by Download** [comment]
@viggis75 Your config looks ok to me. The Docker story sounds mysterious... You should be able to get some logging from the filter by setting the `com.stijndewitt.undertow.cors.Filter` logger's level. Then watch the server logs to see what happens.

E.g. there is this logging line in the [source](https://github.com/Download/undertow-cors-filter/blob/master/src/main/java/com/stijndewitt/undertow/cors/Filter.java#L670):

```java
LOG.fine("undertow-cors-filter: handling request " + url);
```

So you should be able to see whether it is handling your request or not.

**Comment by viggis75** [comment]
I can see that the request is handled for the OPTIONS call, this is the output:
21:12:10,727 INFO  [com.stijndewitt.undertow.cors.Filter] (default task-1) undertow-cors-filter: CORS headers added for origin http://localhost:3000

But, the browser don't like the duplicate headers and gives me this:
Access to XMLHttpRequest at 'http://localhost:8280/zupplyio-organizationservice/organizations/888888888' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000, http://localhost:3000', but only one is allowed.

**Comment by viggis75** [comment]
Response headers for the OPTIONS call:
Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization,Content-Type,Link,X-Total-Count,Range
Access-Control-Allow-Headers: authorization
Access-Control-Allow-Methods: GET,POST
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Expose-Headers: Accept-Ranges,Content-Length,Content-Range,ETag,Link,Server,X-Total-Count
Access-Control-Max-Age: 864000
Connection: keep-alive
Content-Length: 0
Date: Sun, 13 Jan 2019 21:12:10 GMT

**Comment by viggis75** [comment]
I have also changed the hasHeader method and output the headers, and at the point the filter is run, no cors headers are currently set, hence the filter adds it. But it seems some filter later in the filter chain adds it, which I find strange. Not sure how Undertow works under the hood, and what can cause it to add it.
https://github.com/Download/undertow-cors-filter/blob/d446a5bd77917d4350f6c26a2aa5e365a760ebcf/src/main/java/com/stijndewitt/undertow/cors/Filter.java#L738

**Comment by Download** [comment]
Hi @viggis75 I suspect that some other piece of software is setting the headers.

What I would try: Just install an empty Wildfly and only add the CORS filter and then check the headers on some requests. I am betting you will only 1 of each header. If you look at the headers you pasted you can see that one is coming from the CORS filter (same values as specified in your config) and the other is coming from somewhere else (different values).

What is responding to your request? Something is adding those headers. Is it a servlet, a filter, a [ContainerRequestFilter](https://dennis-xlc.gitbooks.io/restful-java-with-jax-rs-2-0-2rd-edition/en/part1/chapter12/server_side_filters.html) etc? Because I think that you will find that one of these things is doing it. Try to create a picture of all the components that are taking part in the request; one of these components is the culprit. As far as I can tell from what you are saying here, your config of the CORS filter is correct and works as planned. It's just that there is an extra piece of code that is also setting headers (and not checking if they exist already...)
